# Generated by Django 5.0.1 on 2024-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customer_id",
            field=models.IntegerField(default=0),
        ),
    ]
