# Generated by Django 5.0.1 on 2024-02-19 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_app", "0002_product_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="customer_id",
        ),
    ]
