version: '3'

services:
  customerdb:
    image: postgres
    container_name: customer_db_container
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
    volumes:
      - customer_data:/var/lib/postgresql/data
    networks:
      inventory_network:
        ipv4_address: 172.20.0.2

  customer_web:
    build: ./customer_web
    container_name: customer_web_container
    ports:
      - "8001:8000"
    depends_on:
      - customerdb
    networks:
      inventory_network:
        ipv4_address: 172.20.0.3
  
    environment:
      DB_NAME=customer
      DB_USER=customer
      DB_PASSWORD=customer
      DB_HOST=customer_db
      DB_PORT=5432

  product_db:
    image: product_db
    container_name: product_db_container
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      inventory_network:
        ipv4_address: 172.20.0.4

  product_web:
    build: ./product_web
    container_name: product_web_container
    ports:
      - "8002:8000"
    depends_on:
      - product_db
    networks:
      inventory_network:
        ipv4_address: 172.20.0.5
  environment:
      DB_NAME=product
      DB_USER=product
      DB_PASSWORD=product
      DB_HOST=product_db
      DB_PORT=5432

networks:
  inventory_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"

volumes:
  customer_data:
  product_data:
