# Generated by Django 5.0.1 on 2024-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
