# Generated by Django 5.0.1 on 2024-02-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_app", "0003_alter_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="identifier",
            field=models.IntegerField(default=0),
        ),
    ]
