# Generated by Django 5.0.1 on 2024-02-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_app", "0006_remove_customer_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="product_id",
            field=models.IntegerField(default=0),
        ),
    ]
