name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      
    - name: Build and push customerweb image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/customerweb:latest ./customer
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/customerweb:latest
      
    - name: Build and push productweb image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/productweb:latest ./product
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/productweb:latest
