name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Customer Service
        run: |
          docker build -t rumeebs23/customer:latest -f ./inventory-Management-System/customer/Dockerfile .
          docker push rumeebs23/customer:latest

      - name: Build and Push Product Service
        run: |
          docker build -t rumeebs23/product:latest -f ./inventory-Management-System/product/Dockerfile .
          docker push rumeebs23/product:latest